[package]
name = "percent_encoding"
version = "2023.11.9"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
percent-encoding = { version = "*" }
anyhow = { version = "*" }